# Generated by Django 3.2.9 on 2021-11-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211104_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorDTOModel',
            new_name='AuthorModel',
        ),
    ]
